# Generated by Django 6.0.4 on 2026-05-01 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('homes', '0002_home_advance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='homes.home'),
        ),
    ]
