# Generated by Django 5.2.8 on 2026-05-02 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('subscription', 'Monthly Subscription'), ('special_program', 'Special Program Fund'), ('previous_balance', 'Previous Balance'), ('other', 'Other')], default='subscription', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finance.specialprogram'),
        ),
        migrations.AddField(
            model_name='specialprogram',
            name='per_member_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount to be collected from each member', max_digits=10),
        ),
    ]
