# Generated by Django 6.0.4 on 2026-05-01 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('homes', '0002_home_advance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='home_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='homes.home'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Committee (Admin)'), ('staff', 'Staff'), ('home', 'Home Member')], default='staff', max_length=20),
        ),
    ]
