# Generated by Django 6.0.4 on 2026-05-01 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Family Name or Head of Household', max_length=150)),
                ('house_name', models.CharField(blank=True, max_length=150)),
                ('home_type', models.CharField(choices=[('member', 'Member Home'), ('non_member', 'Non-Member Home')], default='member', max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fee_exception', models.BooleanField(default=False, help_text='Check if this home is exempted from paying fees (e.g., poor family)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, help_text='Class/Grade in Madrasa', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='homes.home')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
