# Generated by Django 6.0.4 on 2026-05-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='advance_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Money paid in advance by this home', max_digits=10),
        ),
    ]
