# Generated by Django 6.0.4 on 2026-05-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_home_advance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='area',
            field=models.CharField(blank=True, help_text='Locality or area of residence', max_length=150),
        ),
    ]
