# Generated by Django 5.2.8 on 2026-05-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_home_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='name_en',
            field=models.CharField(blank=True, help_text='Name in English', max_length=150),
        ),
    ]
