# Generated by Django 5.2.8 on 2026-05-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_home_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='uid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Home ID'),
        ),
    ]
