# Generated by Django 5.2.8 on 2026-05-25 16:47

from django.db import migrations

def populate_areas(apps, schema_editor):
    Home = apps.get_model('homes', 'Home')
    Area = apps.get_model('homes', 'Area')

    for home in Home.objects.all():
        if home.area:
            area_name = home.area.strip()
            if area_name:
                area_obj, created = Area.objects.get_or_create(name=area_name)
                home.area_new = area_obj
                home.save()

def reverse_populate_areas(apps, schema_editor):
    Home = apps.get_model('homes', 'Home')
    for home in Home.objects.all():
        if home.area_new:
            home.area = home.area_new.name
            home.save()

class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0006_area_home_area_new'),
    ]

    operations = [
        migrations.RunPython(populate_areas, reverse_code=reverse_populate_areas),
    ]
