# Generated by Django 5.2.8 on 2026-05-25 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0007_migrate_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='area',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='area_new',
            new_name='area',
        ),
        migrations.AlterField(
            model_name='home',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homes', to='homes.area', verbose_name='Area/Locality'),
        ),
    ]
