# Generated by Django 5.2.8 on 2026-05-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0008_remove_home_area_new_alter_home_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['id']},
        ),
    ]
