# Generated by Django 5.2.8 on 2026-05-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0009_alter_area_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['id']},
        ),
    ]
